name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy
        pip install pygame-ce
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') || echo "Pylint exited with exit code $? but it doesn't really matter."
        mypy $(git ls-files '*.py') || echo "Mypy exited with exit code $? but I don't presently care"
